"""
extract_icons.py
----------------
Reads the LMS Icons.jsx file and extracts only the named exports
required by the SAT LMS Interactive Demo package.

Usage (run from inside sat-lms-interactive-demo/):
  python scripts/extract_icons.py

Output:
  components/icons/DemoIcons.jsx
"""

import re
import os
import sys

# --------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------

ICONS_SOURCE = (
    r"D:\CodeBase\prism-learning-ui\apps\prism-lms-ui\src\pages\Icons.jsx"
)
OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "components", "icons", "DemoIcons.jsx"
)

NEEDED = {
    "SearchIcon",
    "CloseIcon",
    "ChevronRightIcon",
    "ChevronLeftIcon",
    "ChevronDownIcon",
    "PlayIcon",
    "BookOpenIcon",
    "PencilSquareIcon",
    "ClipboardDocumentListIcon",
    "CheckIcon",
    "CompleteIcon",
    "InProgressIcon",
    "CircleIcon",
    "SkippedCheckmarkIcon",
    "ExclamationTriangleIcon",
    "UQEIcon",
    "ClockIcon",
    "FocusViewIcon",
    "FullViewIcon",
    "ListBulletIcon",
    "CementingQuizIcon",
    "TrophyOutlineIcon",
    "ExpandAllIcon",
    "CollapseAllIcon",
    "RemedialIcon",
    "RevisionActivityIcon",
    "ArrowRightIcon",
    "ArrowLeftIcon",
    "CheckCircleIcon",
    "LightningBoltIcon",
    "RefreshIcon",
    "DocumentIcon",
    "AssessmentIcon",
    "PaceLogoGreen",
    "GridIcon",
    "DiagnosticIcon",
    "LightningBoltOutlineIcon",
    "SparklesIcon",
}

# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

def read_source(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def extract_blocks(source, needed):
    """
    Walk the source line-by-line and pull out each export block
    for the icons we need. Handles:
      - Arrow-function components: export const Foo = (...) => (...)
      - Regular-function components: export const Foo = (...) => { ... }
      - forwardRef components: skipped (animated icons use motion — not needed)
    """
    lines = source.split("\n")
    total = len(lines)
    blocks = {}
    i = 0

    # Find the line where animated imports begin so we stop there
    animated_start = total
    for idx, line in enumerate(lines):
        if "Animated Icons" in line or "motion/react" in line:
            animated_start = idx
            break

    while i < animated_start:
        line = lines[i]

        # Match: export const IconName = ...
        m = re.match(r"^export const (\w+)\s*=", line)
        if m:
            name = m.group(1)
            if name in needed:
                # Collect until we hit a blank line followed by a new export
                # or end of pre-animated section
                start = i
                # Check if it's a forwardRef (skip)
                if "forwardRef" in line or (i + 1 < total and "forwardRef" in lines[i + 1]):
                    i += 1
                    continue

                # Find the end of this block: look for the closing paren/brace
                # at column 0 followed by blank line / next export
                j = i + 1
                depth = 0
                # Count opening parens/braces on the first line
                for ch in line:
                    if ch in "({":
                        depth += 1
                    elif ch in ")}":
                        depth -= 1

                if depth <= 0 and j < total:
                    # LightningBoltIcon uses a function body — handle it
                    pass

                while j < animated_start:
                    for ch in lines[j]:
                        if ch in "({":
                            depth += 1
                        elif ch in ")}":
                            depth -= 1
                    if depth <= 0:
                        # Include the closing line
                        j += 1
                        # Skip trailing blank lines that belong to this block
                        break
                    j += 1

                block = "\n".join(lines[start:j])
                blocks[name] = block.rstrip()
                i = j
                continue
        i += 1

    return blocks


def build_output(blocks, needed):
    header = '''\
/**
 * DemoIcons.jsx
 * -------------
 * Extracted subset of the LMS Icons.jsx file.
 * Generated by scripts/extract_icons.py — do not edit manually.
 *
 * Contains only the icons used by the SAT LMS Interactive Demo.
 * SVG paths are identical to the source; only the unused exports are removed.
 */
'''
    parts = [header]
    found = sorted(blocks.keys())
    missing = sorted(needed - set(found))

    for name in found:
        parts.append(blocks[name])
        parts.append("")

    if missing:
        parts.append("// NOTE: The following icons were listed as needed but not found in the source:")
        for name in missing:
            parts.append(f"// - {name}")
        parts.append("")

    return "\n".join(parts)


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    if not os.path.exists(ICONS_SOURCE):
        print(f"ERROR: Source file not found:\n  {ICONS_SOURCE}")
        sys.exit(1)

    print(f"Reading: {ICONS_SOURCE}")
    source = read_source(ICONS_SOURCE)

    print(f"Extracting {len(NEEDED)} icons...")
    blocks = extract_blocks(source, NEEDED)

    output = build_output(blocks, NEEDED)

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(output)

    found = sorted(blocks.keys())
    missing = sorted(NEEDED - set(found))

    print(f"\nDone. Written to:\n  {OUTPUT_PATH}")
    print(f"\nExtracted ({len(found)}):")
    for name in found:
        print(f"  ✓  {name}")
    if missing:
        print(f"\nNot found ({len(missing)}) — will need manual addition:")
        for name in missing:
            print(f"  ✗  {name}")


if __name__ == "__main__":
    main()
