export const moreWorkLanes = [
  {
    id: 'product',
    eyebrow: 'Product Systems',
    title: 'Product Design',
    shortTitle: 'Product',
    accentVar: '--color-accent-orange',
    softVar: '--color-surface-peach',
    metric: '7+ tools & systems',
    proof: 'Flows, specs, dashboards, trackers, diagnostics, and decision loops.',
    description: 'Shaping messy product logic into clear decisions, usable flows, and shipped interfaces.',
    cards: [
      {
        slug: 'sk-studies',
        title: 'SK Studies',
        tag: 'Study workflow',
        note: 'Structured learning journeys with clearer next steps.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Product Systems',
          title: 'SK Studies',
          role: 'Product design, learning workflow',
          year: '2024',
          context: 'A study workflow shaped around clearer learning momentum.',
          description: 'A lean product context for the SK Studies work, showing how structured learning journeys, visible next steps, and repeatable study behavior came together.',
          outcome: 'Made the study path easier to understand before final assets are added.',
          tools: ['Product logic', 'UX flows', 'Interface design'],
          stats: ['Study workflow', 'Learning journeys', 'Next-step clarity'],
        },
      },
      {
        slug: 'personalized-study-planner',
        title: 'Personalized Study Planner',
        tag: 'Planning system',
        note: 'A planning flow that converts goals into a usable prep path.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Product Systems',
          title: 'Personalized Study Planner',
          role: 'Product design, planning logic',
          year: '2024',
          context: 'A goal-to-plan experience for learners who need a usable prep route.',
          description: 'A planning flow that turns target score, available time, and prep intent into a path a student can actually follow.',
          outcome: 'Translated abstract prep goals into a visible plan structure.',
          tools: ['Planning logic', 'UX writing', 'Flow design'],
          stats: ['Goal input', 'Prep path', 'Decision support'],
        },
      },
      {
        slug: 'sigma-x',
        title: 'SIGma-X',
        tag: 'Internal product',
        note: 'Complex capability translated into a usable operating interface.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Product Systems',
          title: 'SIGma-X',
          role: 'Internal product UX',
          year: '2024',
          context: 'A complex internal capability that needed a calmer operating surface.',
          description: 'A product interface pass focused on turning dense internal logic into clear controls, readable status, and useful operating cues.',
          outcome: 'Made the product easier to reason through for internal teams.',
          tools: ['Information architecture', 'Dashboard UX', 'Interaction design'],
          stats: ['Internal product', 'Operating UI', 'Complex logic'],
        },
      },
      {
        slug: 'scholaranium',
        title: 'Scholaranium',
        tag: 'Learning UX revamp',
        note: 'Practice, review, and learning loops rebuilt for clarity.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Product Systems',
          title: 'Scholaranium',
          role: 'Learning UX revamp',
          year: '2023',
          context: 'A learning product surface where practice and review needed a clearer loop.',
          description: 'A revamp pass around how students enter practice, understand review, and return to learning without losing their place.',
          outcome: 'Clarified the learning loop and reduced ambiguity between practice and review.',
          tools: ['Learning UX', 'Review flows', 'Visual hierarchy'],
          stats: ['Practice loop', 'Review system', 'Learning clarity'],
        },
      },
      {
        slug: 'study-streak-rings',
        title: 'Study Streak Rings',
        tag: 'Behavior loop',
        note: 'Motivation mechanics designed around consistency and return behavior.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Product Systems',
          title: 'Study Streak Rings',
          role: 'Behavior design',
          year: '2024',
          context: 'A behavior loop for helping study consistency feel visible and rewarding.',
          description: 'A motivation mechanic shaped around return behavior, progress memory, and the small signals that make consistency easier to continue.',
          outcome: 'Gave consistency a visible product language.',
          tools: ['Behavior design', 'Gamified UX', 'Progress states'],
          stats: ['Consistency loop', 'Return cue', 'Progress memory'],
        },
      },
      {
        slug: 'execution-tracker',
        title: 'Execution Tracker',
        tag: 'Progress visibility',
        note: 'A tracking layer for making effort, gaps, and next actions visible.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Product Systems',
          title: 'Execution Tracker',
          role: 'Progress system UX',
          year: '2024',
          context: 'A tracker for turning messy execution into visible progress and gaps.',
          description: 'A visibility layer that helps users understand what moved, what is stuck, and what deserves attention next.',
          outcome: 'Made progress easier to inspect without reading through scattered notes.',
          tools: ['Tracking UX', 'Status design', 'Progress systems'],
          stats: ['Effort visible', 'Gap tracking', 'Next actions'],
        },
      },
      {
        slug: 'climatics',
        title: 'Climatics',
        tag: 'Side product',
        note: 'Weather app experiment focused on clean utility and visual hierarchy.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Product Systems',
          title: 'Climatics',
          role: 'Side product experiment',
          year: '2023',
          context: 'A compact weather app experiment built around everyday utility.',
          description: 'A side product focused on clean hierarchy, useful weather states, and a fast read of what matters right now.',
          outcome: 'Explored how utility apps can feel simpler without feeling thin.',
          tools: ['Product UI', 'Visual hierarchy', 'Utility design'],
          stats: ['Weather utility', 'Fast scan', 'Side product'],
        },
      },
    ],
  },
  {
    id: 'web',
    eyebrow: 'Web Services',
    title: 'Web Design & Build',
    shortTitle: 'Web Build',
    accentVar: '--color-accent-lavender',
    softVar: '--color-surface-lilac',
    metric: '150+ pages built',
    proof: 'Content structure, page design, interaction logic, and implementation-ready layouts.',
    description: 'Marketing sites, landing pages, blogs, explainers, and conversion journeys built end to end.',
    cards: [
      {
        slug: 'egmat-blogs',
        title: 'e-GMAT Blogs',
        tag: 'SEO content system',
        note: 'High-volume content pages shaped for readability and search intent.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Web Services',
          title: 'e-GMAT Blogs',
          role: 'Web design, SEO content system',
          year: '2023-2025',
          context: 'A high-volume blog system where readability and search intent had to work together.',
          description: 'A web system pass across content-heavy pages, focused on hierarchy, reusable sections, and making long-form pages easier to scan.',
          outcome: 'Supported a scalable publishing surface for search-led content.',
          tools: ['Web design', 'SEO structure', 'Reusable page patterns'],
          stats: ['150+ pages', 'SEO intent', 'Content system'],
        },
      },
      {
        slug: 'nerdypixel-studios',
        title: 'NerdyPixel Studios',
        tag: 'Agency landing page',
        note: 'A focused brand surface for positioning, trust, and lead capture.',
        actionType: 'internal-route',
        embedUrl: 'https://nerdypixelstudios.ca',
        externalUrl: 'https://nerdypixelstudios.ca',
        details: {
          eyebrow: 'Web Services',
          title: 'NerdyPixel Studios',
          role: 'Landing page design and build',
          year: '2025',
          context: 'A studio landing page for positioning, trust, and lead capture.',
          description: 'A focused brand surface built to explain what the studio does quickly, while keeping a path open for prospective clients.',
          outcome: 'Turned a broad service story into a tighter public-facing surface.',
          tools: ['Landing page', 'Brand positioning', 'Conversion UX'],
          stats: ['Agency surface', 'Lead capture', 'Brand trust'],
        },
      },
      {
        slug: 'free-trial-page',
        title: 'Free Trial Page',
        tag: 'Conversion page',
        note: 'Landing-page structure refined around clarity and action.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Web Services',
          title: 'Free Trial Page',
          role: 'Conversion page design',
          year: '2024',
          context: 'A conversion page where the offer, proof, and action needed to line up quickly.',
          description: 'A landing-page structure designed around clarity, motivation, and a direct next action.',
          outcome: 'Made the page easier to understand and act on.',
          tools: ['Conversion UX', 'Landing-page structure', 'Copy hierarchy'],
          stats: ['Offer clarity', 'Action path', 'Conversion page'],
        },
      },
      {
        slug: 'coach-connect',
        title: 'Coach Connect',
        tag: 'Product explainer',
        note: 'A product page built to explain value quickly and visually.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Web Services',
          title: 'Coach Connect',
          role: 'Product explainer page',
          year: '2024',
          context: 'A product page that needed to explain value before users lost patience.',
          description: 'A page design focused on making the product promise, workflow, and reasons to believe clear in a quick scan.',
          outcome: 'Improved the first-read story for a coaching product.',
          tools: ['Product storytelling', 'Page design', 'Visual explanation'],
          stats: ['Explainer page', 'Value clarity', 'Product story'],
        },
      },
      {
        slug: 'm7-admits-page',
        title: 'M7 Admits Page',
        tag: 'Interactive page',
        note: 'A richer admissions story with carousel and card interactions.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Web Services',
          title: 'M7 Admits Page',
          role: 'Interactive web page',
          year: '2024',
          context: 'An admissions story that needed richer browsing than a static page could give.',
          description: 'A web page with carousel and card interactions to help outcomes, schools, and proof feel more inspectable.',
          outcome: 'Created a more active way to explore admissions proof.',
          tools: ['Interactive UI', 'Carousel UX', 'Proof design'],
          stats: ['Interactive page', 'Admissions story', 'Card system'],
        },
      },
      {
        slug: 'growth-pages',
        title: 'Growth Pages',
        tag: 'Marketing system',
        note: 'Reusable interaction patterns across public-facing web pages.',
        actionType: 'internal-route',
        details: {
          eyebrow: 'Web Services',
          title: 'Growth Pages',
          role: 'Marketing page system',
          year: '2023-2025',
          context: 'A collection of public-facing pages that needed repeatable quality at volume.',
          description: 'Reusable page patterns for marketing, content, proof, and conversion moments across web surfaces.',
          outcome: 'Helped repeated page production stay visually and structurally consistent.',
          tools: ['Web systems', 'Interaction patterns', 'Page production'],
          stats: ['Reusable patterns', 'Growth pages', 'Public web'],
        },
      },
    ],
  },
  {
    id: 'marketing',
    eyebrow: 'Visual Systems',
    title: 'Marketing & Branding',
    shortTitle: 'Branding',
    accentVar: '--color-accent-green',
    softVar: '--color-surface-mint',
    metric: 'Campaigns, logos & video collateral',
    proof: 'From individual creatives to repeatable visual systems built for recall.',
    description: 'Campaign, logo, and content systems built for visual recall.',
    cards: [
      {
        slug: 'encubate',
        title: 'Encubate',
        tag: 'Campaign identity',
        note: 'A campaign system shaped across message, look, and launch collateral.',
        actionType: 'image-modal',
        details: {
          eyebrow: 'Visual Systems',
          title: 'Encubate',
          role: 'Campaign identity',
          year: '2024',
          context: 'A campaign identity system shaped across message, launch collateral, and visual recall.',
          description: 'Image-led campaign work will live here as final assets are added.',
          outcome: 'Built a visual container for a campaign story.',
          tools: ['Campaign identity', 'Brand system', 'Launch assets'],
          stats: ['Campaign system', 'Launch collateral', 'Visual recall'],
        },
      },
      {
        slug: 'logo-design',
        title: 'Logo Design',
        tag: 'Brand marks',
        note: 'Identity explorations for brands, initiatives, and internal products.',
        actionType: 'image-modal',
        details: {
          eyebrow: 'Visual Systems',
          title: 'Logo Design',
          role: 'Brand mark exploration',
          year: '2023-2025',
          context: 'Identity explorations across brands, initiatives, and internal products.',
          description: 'A gallery-ready slot for final logo explorations and brand mark assets.',
          outcome: 'Gave multiple ideas a memorable visual mark.',
          tools: ['Logo design', 'Identity systems', 'Visual exploration'],
          stats: ['Brand marks', 'Identity work', 'Explorations'],
        },
      },
      {
        slug: 'youtube-growth-system',
        title: 'YouTube Growth System',
        tag: 'Video design ops',
        note: 'Thumbnail, shorts, community, and publishing systems for consistency.',
        actionType: 'image-modal',
        details: {
          eyebrow: 'Visual Systems',
          title: 'YouTube Growth System',
          role: 'Video design operations',
          year: '2024',
          context: 'A repeatable content system for thumbnails, shorts, community, and publishing consistency.',
          description: 'A visual operations system for making recurring video assets feel consistent without slowing production.',
          outcome: 'Made video collateral faster to produce and easier to recognize.',
          tools: ['Thumbnail systems', 'Content operations', 'Visual templates'],
          stats: ['Thumbnails', 'Shorts', 'Publishing system'],
        },
      },
      {
        slug: 'student-success-creatives',
        title: 'Student Success Creatives',
        tag: 'Story collateral',
        note: 'Visual systems for turning outcomes into credible proof.',
        actionType: 'image-modal',
        details: {
          eyebrow: 'Visual Systems',
          title: 'Student Success Creatives',
          role: 'Outcome storytelling collateral',
          year: '2023-2025',
          context: 'Outcome stories that needed to feel credible, scannable, and repeatable.',
          description: 'A visual system for turning student outcomes into social and page-ready proof.',
          outcome: 'Made success stories easier to trust at a glance.',
          tools: ['Story collateral', 'Proof design', 'Social systems'],
          stats: ['Outcome proof', 'Story assets', 'Credibility'],
        },
      },
      {
        slug: 'webinar-campaigns',
        title: 'Webinar Campaigns',
        tag: 'Conversion collateral',
        note: 'Event visuals, promotion assets, and funnel-support creatives.',
        actionType: 'image-modal',
        details: {
          eyebrow: 'Visual Systems',
          title: 'Webinar Campaigns',
          role: 'Event campaign collateral',
          year: '2023-2025',
          context: 'Event promotion assets built to support awareness, registration, and follow-through.',
          description: 'A campaign collateral slot for webinar visuals, promotion assets, and funnel support.',
          outcome: 'Kept event promotion clear and visually consistent.',
          tools: ['Event visuals', 'Campaign design', 'Conversion collateral'],
          stats: ['Event assets', 'Promotion system', 'Funnel support'],
        },
      },
      {
        slug: 'social-creatives',
        title: 'Social Creatives',
        tag: 'Attention design',
        note: 'Fast-turnaround assets built for scanning, recall, and action.',
        actionType: 'image-modal',
        details: {
          eyebrow: 'Visual Systems',
          title: 'Social Creatives',
          role: 'Fast-turnaround creative design',
          year: '2023-2025',
          context: 'Social assets built to be understood quickly in crowded feeds.',
          description: 'A gallery-ready slot for fast-turnaround creatives built around scanning, recall, and action.',
          outcome: 'Helped recurring social messages keep a stronger visual memory.',
          tools: ['Social design', 'Attention design', 'Fast iteration'],
          stats: ['Scanning', 'Recall', 'Action'],
        },
      },
    ],
  },
];

export function getMoreWorkDetailItems() {
  return moreWorkLanes.flatMap((lane) => (
    lane.cards
      .filter((card) => card.actionType === 'internal-route')
      .map((card) => ({
        ...card,
        laneId: lane.id,
        laneTitle: lane.title,
        accentVar: lane.accentVar,
        softVar: lane.softVar,
      }))
  ));
}

export function getMoreWorkBySlug(slug) {
  return getMoreWorkDetailItems().find((item) => item.slug === slug);
}
