/**
 * DemoIcons.jsx
 * -------------
 * Extracted subset of the LMS Icons.jsx file.
 * Generated by scripts/extract_icons.py — do not edit manually.
 *
 * Contains only the icons used by the SAT LMS Interactive Demo.
 * SVG paths are identical to the source; only the unused exports are removed.
 */

export const ArrowLeftIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    className={className}
    {...props}
  >
    <path d="M11 17l-5-5m0 0l5-5m-5 5h12" />
  </svg>
)

export const ArrowRightIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <line x1="5" y1="12" x2="19" y2="12" />
    <polyline points="12 5 19 12 12 19" />
  </svg>
)

export const AssessmentIcon = ({ size = 12, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2" />
    <rect x="9" y="3" width="6" height="4" rx="1" />
    <path d="m9 14 2 2 4-4" />
  </svg>
)

export const BookOpenIcon = ({ size = 14, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
  </svg>
)

export const CementingQuizIcon = ({ size = 18, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    className={className}
    {...props}
  >
    <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25M9 16.5v.75m3-3v3M15 12v5.25m-4.5-15H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
  </svg>
)

export const CheckCircleIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    {...props}
  >
    <path fillRule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12zm13.36-1.814a.75.75 0 1 0-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 0 0-1.06 1.06l2.25 2.25a.75.75 0 0 0 1.14-.094l3.75-5.25z" clipRule="evenodd" />
  </svg>
)

export const CheckIcon = ({ size = 14, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="4"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M5 13l4 4L19 7" />
  </svg>
)

export const ChevronDownIcon = ({ size = 20, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M19 9l-7 7-7-7" />
  </svg>
)

export const ChevronLeftIcon = ({ size = 16, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 16 16"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M10 12l-4-4 4-4" />
  </svg>
)

export const ChevronRightIcon = ({ size = 16, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 16 16"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M6 12l4-4-4-4" />
  </svg>
)

export const CircleIcon = ({ size = 12, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 12 12"
    fill="none"
    className={className}
    {...props}
  >
    <circle cx="6" cy="6" r="5.5" stroke="currentColor" />
  </svg>
)

export const ClipboardDocumentListIcon = ({ size = 20, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
  </svg>
)

export const ClockIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <circle cx="12" cy="12" r="10" />
    <path d="M12 6v6l4 2" />
  </svg>
)

export const CloseIcon = ({ size = 20, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M18 6 6 18" />
    <path d="m6 6 12 12" />
  </svg>
)

export const CollapseAllIcon = ({ size = 16, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M17 18l-5-5-5 5" />
    <path d="M17 11l-5-5-5 5" />
  </svg>
)

export const CompleteIcon = ({ size = 12, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 12 12"
    fill="none"
    className={className}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6 0C9.31313 0 12 2.68687 12 6C12 9.31313 9.31313 12 6 12C2.68687 12 0 9.31313 0 6C0 2.68687 2.68687 0 6 0ZM4.75402 7.94884L3.28508 6.47868C3.03482 6.22828 3.03477 5.81993 3.28508 5.56958C3.53544 5.31927 3.9456 5.32084 4.19414 5.56958L5.22974 6.60599L7.80596 4.02977C8.05632 3.77941 8.4647 3.77941 8.71501 4.02977C8.96537 4.28008 8.96502 4.68882 8.71501 4.93883L5.68353 7.97031C5.43353 8.22031 5.02478 8.22067 4.77447 7.97031C4.76744 7.96328 4.76065 7.95613 4.75402 7.94884Z"
      fill="#32CD32"
    />
  </svg>
)

export const DiagnosticIcon = ({ size = 18, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 26 26"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.75"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    {/* Magnifying glass circle - positioned to allow stroke breathing room */}
    <circle cx="12" cy="12" r="7.5" />
    {/* Magnifying glass handle */}
    <path d="M17.5 17.5L23 23" strokeWidth="2" />
    {/* Heartbeat line inside - centered and scaled */}
    <path d="M7 12h1.8l1.2-2.5 1.8 5 1.2-2.5H16" strokeWidth="1.5" />
  </svg>
)

export const DocumentIcon = ({ size = 12, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
    <polyline points="14 2 14 8 20 8" />
    <line x1="16" y1="13" x2="8" y2="13" />
    <line x1="16" y1="17" x2="8" y2="17" />
    <polyline points="10 9 9 9 8 9" />
  </svg>
)

export const ExclamationTriangleIcon = ({ size = 48, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    {...props}
  >
    <path
      fillRule="evenodd"
      d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003ZM12 8.25a.75.75 0 0 1 .75.75v3.75a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75Zm0 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z"
      clipRule="evenodd"
    />
  </svg>
)

export const ExpandAllIcon = ({ size = 16, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M7 6l5 5 5-5" />
    <path d="M7 13l5 5 5-5" />
  </svg>
)

export const FocusViewIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    {...props}
  >
    <path d="M1,8c-.55,0-1-.45-1-1v-2C0,2.24,2.24,0,5,0h2c.55,0,1,.45,1,1s-.45,1-1,1h-2c-1.65,0-3,1.35-3,3v2c0,.55-.45,1-1,1Zm7,15c0-.55-.45-1-1-1h-2c-1.65,0-3-1.35-3-3v-2c0-.55-.45-1-1-1s-1,.45-1,1v2c0,2.76,2.24,5,5,5h2c.55,0,1-.45,1-1Zm16-4v-2c0-.55-.45-1-1-1s-1,.45-1,1v2c0,1.65-1.35,3-3,3h-2c-.55,0-1,.45-1,1s.45,1,1,1h2c2.76,0,5-2.24,5-5Zm0-12v-2c0-2.76-2.24-5-5-5h-2c-.55,0-1,.45-1,1s.45,1,1,1h2c1.65,0,3,1.35,3,3v2c0,.55,.45,1,1,1s1-.45,1-1Zm-14.48,10.19l2.48-1.66,2.52,1.64c.33,.21,.75,.2,1.06-.04,.31-.24,.43-.64,.31-1.01l-.9-2.73,2.17-1.77c.29-.25,.4-.65,.27-1.02s-.48-.6-.86-.6h-2.75l-.97-2.61c-.13-.36-.48-.6-.86-.6s-.73,.24-.86,.6l-.97,2.61h-2.75c-.38,0-.73,.24-.86,.6-.13,.36-.03,.77,.27,1.01l2.18,1.77-.86,2.76c-.12,.37,.01,.78,.32,1.01,.16,.12,.36,.18,.55,.18,.18,0,.36-.05,.51-.15Z"/>
  </svg>
)

export const FullViewIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    {...props}
  >
    <path d="M22.2,2.163a4.992,4.992,0,0,0-4.1-1.081l-3.822.694A4,4,0,0,0,12,3.065,4,4,0,0,0,9.716,1.776L5.9,1.082A5,5,0,0,0,0,6V16.793a5,5,0,0,0,4.105,4.919l6.286,1.143a9,9,0,0,0,3.218,0L19.9,21.712A5,5,0,0,0,24,16.793V6A4.983,4.983,0,0,0,22.2,2.163ZM11,20.928c-.084-.012-.168-.026-.252-.041L4.463,19.745A3,3,0,0,1,2,16.793V6A3,3,0,0,1,5,3a3.081,3.081,0,0,1,.54.049l3.82.7A2,2,0,0,1,11,5.712Zm11-4.135a3,3,0,0,1-2.463,2.952l-6.285,1.142c-.084.015-.168.029-.252.041V5.712a2,2,0,0,1,1.642-1.968l3.821-.7A3,3,0,0,1,22,6Z"/>
  </svg>
)

export const InProgressIcon = ({ size = 12, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 12 12"
    fill="none"
    className={className}
    {...props}
  >
    <path d="M4.83974 9.8109C4.88032 9.61906 5.06789 9.49663 5.25868 9.53743C5.44946 9.57823 5.57123 9.76682 5.53066 9.95866L5.15839 11.7187C5.11782 11.9105 4.93027 12.033 4.73949 11.9922C4.5487 11.9514 4.42693 11.7628 4.4675 11.5709L4.83974 9.8109Z" fill="#94A3B8"/>
    <path d="M6.72833 9.5339C6.91912 9.49311 7.10666 9.61556 7.14724 9.8074L7.51951 11.5674C7.56009 11.7592 7.43831 11.9479 7.24752 11.9887C7.05674 12.0295 6.86917 11.907 6.82859 11.7152L6.45635 9.95516C6.41577 9.76331 6.53754 9.5747 6.72833 9.5339Z" fill="#94A3B8"/>
    <path d="M3.42519 9.01631C3.53989 8.85762 3.76082 8.82249 3.91864 8.93783C4.07646 9.05317 4.1114 9.27533 3.9967 9.43402L2.9444 10.8899C2.82969 11.0486 2.60876 11.0837 2.45094 10.9684C2.29312 10.853 2.25818 10.6309 2.37289 10.4722L3.42519 9.01631Z" fill="#94A3B8"/>
    <path d="M8.07207 8.93312C8.22989 8.81778 8.45082 8.85291 8.56553 9.01161L9.61785 10.4675C9.73256 10.6262 9.69759 10.8483 9.53977 10.9637C9.38196 11.079 9.16105 11.0438 9.04634 10.8852L7.99402 9.42929C7.87931 9.2706 7.91426 9.04846 8.07207 8.93312Z" fill="#94A3B8"/>
    <path d="M9.05295 7.83786C9.15049 7.66799 9.36653 7.60979 9.53547 7.70787L11.0853 8.60765C11.2542 8.70573 11.3121 8.92296 11.2146 9.09284C11.117 9.2627 10.901 9.3209 10.7321 9.22283L9.18225 8.32305C9.01331 8.22497 8.95541 8.00773 9.05295 7.83786Z" fill="#94A3B8"/>
    <path d="M2.45254 7.70744C2.62148 7.60936 2.83752 7.66758 2.93506 7.83746C3.03259 8.00733 2.97472 8.22454 2.80579 8.32262L1.25595 9.2224C1.08701 9.32048 0.870998 9.26228 0.773457 9.09241C0.675918 8.92254 0.733791 8.7053 0.902729 8.60722L2.45254 7.70744Z" fill="#94A3B8"/>
    <path d="M2.09704 6.11886C2.29114 6.09826 2.4651 6.23979 2.48559 6.43497C2.50607 6.63015 2.36532 6.80507 2.17122 6.82566L0.390522 7.01463C0.196419 7.03523 0.0224637 6.8937 0.00198026 6.69852C-0.018503 6.50334 0.122245 6.32842 0.316349 6.30782L2.09704 6.11886Z" fill="#94A3B8"/>
    <path d="M9.51439 6.43013C9.53488 6.23496 9.70883 6.09345 9.90293 6.11405L11.6837 6.30299C11.8777 6.32359 12.0185 6.49851 11.998 6.69369C11.9775 6.88887 11.8036 7.03039 11.6095 7.0098L9.82876 6.82086C9.63465 6.80026 9.49391 6.62531 9.51439 6.43013Z" fill="#94A3B8"/>
    <path d="M0.260675 4.18861C0.320951 4.00207 0.520205 3.89997 0.705717 3.96058L2.40773 4.51665C2.59325 4.57726 2.69476 4.77765 2.63448 4.96419C2.5742 5.15072 2.37495 5.25281 2.18944 5.1922L0.487451 4.63612C0.301942 4.57551 0.200406 4.37515 0.260675 4.18861Z" fill="#94A3B8"/>
    <path d="M11.2817 3.96045C11.4672 3.89984 11.6664 4.00194 11.7267 4.18848C11.787 4.37502 11.6855 4.57538 11.5 4.63599L9.79794 5.19207C9.61243 5.25268 9.41318 5.1506 9.3529 4.96406C9.29262 4.77752 9.39414 4.57717 9.57965 4.51655L11.2817 3.96045Z" fill="#94A3B8"/>
    <path d="M9.9734 1.98041C10.1183 1.84918 10.3417 1.86094 10.4722 2.00669C10.6027 2.15245 10.591 2.37699 10.446 2.50822L9.11631 3.71215C8.97136 3.84338 8.74806 3.83162 8.61755 3.68587C8.48703 3.54012 8.49876 3.31558 8.64371 3.18434L9.9734 1.98041Z" fill="#94A3B8"/>
    <path d="M7.98245 0.700237C8.06185 0.520951 8.27077 0.440345 8.44907 0.520181C8.62737 0.60002 8.70755 0.810077 8.62816 0.989364L7.89977 2.63416C7.82037 2.81345 7.61147 2.89407 7.43317 2.81424C7.25487 2.7344 7.17468 2.52432 7.25408 2.34503L7.98245 0.700237Z" fill="#94A3B8"/>
    <path d="M5.99418 0C6.18925 6.78652e-06 6.3474 0.159023 6.3474 0.355178V2.15476C6.3474 2.35091 6.18925 2.50993 5.99418 2.50993C5.7991 2.50993 5.64094 2.35092 5.64094 2.15476V0.355178C5.64094 0.159018 5.7991 0 5.99418 0Z" fill="#94A3B8"/>
  </svg>
)

export const LightningBoltIcon = ({ size = 24, className = '', gradientId, ...props }) => {
  // Generate unique gradient ID to avoid conflicts when multiple icons are on page
  const uniqueId = gradientId || `lightning-grad-${Math.random().toString(36).substr(2, 9)}`;
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 512 512"
      className={className}
      {...props}
    >
      <defs>
        <linearGradient id={uniqueId} gradientUnits="userSpaceOnUse" x1="256" x2="256" y1="512" y2="0">
          <stop offset="0" stopColor="#fd5900"/>
          <stop offset="1" stopColor="#ffde00"/>
        </linearGradient>
      </defs>
      <path
        d="m419.498 188.496c-2.49-5.186-7.734-8.496-13.506-8.496h-95.742l79.16-158.291c2.314-4.644 2.08-10.166-.645-14.59-2.753-4.424-7.587-7.119-12.773-7.119h-180c-6.24 0-11.836 3.882-14.033 9.727l-90 240c-1.729 4.614-1.084 9.771 1.699 13.813 2.813 4.043 7.412 6.46 12.334 6.46h100.781l-55.342 223.367c-1.699 6.841 1.582 13.945 7.91 17.08 6.309 3.11 13.942 1.439 18.369-4.072l240-302c3.605-4.512 4.308-10.679 1.788-15.879z"
        fill={`url(#${uniqueId})`}
      />
    </svg>
  );
}

export const LightningBoltOutlineIcon = ({ size = 20, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" />
  </svg>
)

export const ListBulletIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    {...props}
  >
    <path fillRule="evenodd" d="M2.625 6.75a1.125 1.125 0 1 1 2.25 0 1.125 1.125 0 0 1-2.25 0Zm4.875 0A.75.75 0 0 1 8.25 6h12a.75.75 0 0 1 0 1.5h-12a.75.75 0 0 1-.75-.75ZM2.625 12a1.125 1.125 0 1 1 2.25 0 1.125 1.125 0 0 1-2.25 0ZM7.5 12a.75.75 0 0 1 .75-.75h12a.75.75 0 0 1 0 1.5h-12A.75.75 0 0 1 7.5 12Zm-4.875 5.25a1.125 1.125 0 1 1 2.25 0 1.125 1.125 0 0 1-2.25 0Zm4.875 0a.75.75 0 0 1 .75-.75h12a.75.75 0 0 1 0 1.5h-12a.75.75 0 0 1-.75-.75Z" clipRule="evenodd" />
  </svg>
)

export const PencilSquareIcon = ({ size = 14, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
  </svg>
)

export const PlayIcon = ({ size = 14, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    {...props}
  >
    <path d="M8 5.14v14l11-7-11-7z" />
  </svg>
)

export const RefreshIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8" />
    <path d="M21 3v5h-5" />
  </svg>
)

export const RemedialIcon = ({ size = 14, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    className={className}
    {...props}
  >
    {/* Outer circle */}
    <circle cx="12" cy="12" r="9.5" />
    {/* Middle circle */}
    <circle cx="12" cy="12" r="5.5" />
    {/* Center dot (filled) */}
    <circle cx="12" cy="12" r="1.5" fill="currentColor" stroke="none" />
  </svg>
)

export const RevisionActivityIcon = ({ size = 14, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    {...props}
  >
    <path fillRule="evenodd" d="M4.755 10.059a7.5 7.5 0 0 1 12.548-3.364l1.903 1.903h-3.183a.75.75 0 1 0 0 1.5h4.992a.75.75 0 0 0 .75-.75V4.356a.75.75 0 0 0-1.5 0v3.18l-1.9-1.9A9 9 0 0 0 3.306 9.67a.75.75 0 1 0 1.45.388Zm15.408 3.352a.75.75 0 0 0-.919.53 7.5 7.5 0 0 1-12.548 3.364l-1.902-1.903h3.183a.75.75 0 0 0 0-1.5H2.984a.75.75 0 0 0-.75.75v4.992a.75.75 0 0 0 1.5 0v-3.18l1.9 1.9a9 9 0 0 0 15.059-4.035.75.75 0 0 0-.53-.918Z" clipRule="evenodd" />
  </svg>
)

export const SearchIcon = ({ size = 20, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <circle cx="11" cy="11" r="8" />
    <path d="m21 21-4.35-4.35" />
  </svg>
)

export const SkippedCheckmarkIcon = ({ size = 16, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 16 16"
    fill="none"
    className={className}
    {...props}
  >
    <circle cx="8" cy="8" r="7" stroke="#94a3b8" strokeWidth="1.5" strokeDasharray="3 2" />
    <path d="M5 8l2 2 4-4" stroke="#94a3b8" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
)

export const SparklesIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z" />
    <path d="M20 3v4" />
    <path d="M22 5h-4" />
    <path d="M4 17v2" />
    <path d="M5 18H3" />
  </svg>
)

export const TrophyOutlineIcon = ({ size = 14, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    {/* Trophy cup - centered with padding */}
    <path d="M8 4h8v3c0 2.5-1.8 5-4 5s-4-2.5-4-5V4z" />
    {/* Left handle */}
    <path d="M8 5H6a2 2 0 0 0-2 2c0 1.5 1 3 2.5 3" />
    {/* Right handle */}
    <path d="M16 5h2a2 2 0 0 1 2 2c0 1.5-1 3-2.5 3" />
    {/* Stem */}
    <path d="M12 12v3" />
    {/* Base plate */}
    <path d="M9 17h6" />
    {/* Base bottom */}
    <path d="M7 20h10" />
    {/* Stem to base connection */}
    <path d="M12 15v2" />
  </svg>
)

export const UQEIcon = ({ size = 14, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    {/* Circle */}
    <circle cx="12" cy="12" r="9" />
    {/* Question mark curve */}
    <path d="M9.5 9.5c0-1.5 1.1-2.5 2.5-2.5s2.5 1 2.5 2.5c0 1.5-1.5 2-2.5 2.5v1" />
    {/* Question mark dot */}
    <circle cx="12" cy="16.5" r="0.5" fill="currentColor" stroke="none" />
  </svg>
)

// GridIcon — manually added (falls after animated-icons marker in source)
export const GridIcon = ({ size = 24, className = '', ...props }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
    {...props}
  >
    <rect x="3" y="3" width="7" height="7" rx="1" />
    <rect x="14" y="3" width="7" height="7" rx="1" />
    <rect x="14" y="14" width="7" height="7" rx="1" />
    <rect x="3" y="14" width="7" height="7" rx="1" />
  </svg>
)

// PaceLogoGreen — manually added (falls after animated-icons marker in source)
export const PaceLogoGreen = ({ width = 48, className = '', ...props }) => (
  <svg
    width={width}
    height={width * 0.3}
    viewBox="0 0 3570 1071"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    {...props}
  >
    <path d="M3251.23 29.6953C3455.39 29.6953 3601.65 172.914 3563.56 389.265C3560.52 409.071 3554.42 434.972 3545.28 470.015H3024.21C3033.35 538.577 3086.68 581.238 3172 581.238C3239.04 581.238 3310.65 550.766 3362.45 508.105L3453.86 654.37C3370.07 730.55 3240.56 777.782 3121.72 777.782C2896.23 777.782 2763.67 622.375 2803.29 406.024C2842.9 174.437 3047.06 29.6953 3251.23 29.6953ZM3047.06 337.462H3347.21C3357.88 267.377 3303.03 220.145 3222.28 220.145C3155.24 220.145 3085.15 252.141 3047.06 337.462Z" fill="#16a34a" />
    <path d="M2340.72 777.782C2133.51 777.782 1973.53 626.946 2013.15 401.453C2052.76 175.961 2264.54 29.6953 2471.75 29.6953C2608.88 29.6953 2701.81 96.7337 2753.62 197.291L2560.12 306.99C2538.79 264.329 2486.99 238.428 2436.71 238.428C2333.1 238.428 2259.97 313.085 2243.21 401.453C2227.98 491.346 2275.21 569.049 2377.29 569.049C2427.57 569.049 2490.03 543.148 2525.08 500.487L2680.48 610.186C2595.16 710.744 2477.85 777.782 2340.72 777.782Z" fill="#16a34a" />
    <path d="M1689.86 133.3L1703.57 47.9785H1929.06L1804.13 759.499H1578.64L1593.87 668.083C1534.45 735.121 1439.99 777.782 1350.1 777.782C1150.51 777.782 1036.24 626.946 1075.85 404.5C1115.46 180.532 1281.54 29.6953 1484.17 29.6953C1571.02 29.6953 1651.77 67.7853 1689.86 133.3ZM1439.99 569.049C1532.93 569.049 1618.25 491.346 1633.49 404.5C1650.25 311.561 1589.3 238.428 1499.41 238.428C1403.42 238.428 1321.15 313.085 1305.91 404.5C1290.68 491.346 1344 569.049 1439.99 569.049Z" fill="#16a34a" />
    <path d="M607.5 0C807.703 1.39164e-05 970 162.297 970 362.5C970 562.703 807.703 725 607.5 725H285L218 1071H0L87.4844 583H503.545C508.019 583.135 512.528 583.134 517.064 583H532.72C601.706 583 662.932 549.779 701.275 498.464C768.902 427.723 788.275 330.048 742.05 259.684C710.348 211.427 654.606 186.39 593.104 186.379C579.952 183.511 566.293 182 552.28 182H159.372L192 0H607.5Z" fill="#16a34a" />
    <path d="M417.285 241.036C515.408 176.574 637.22 188.656 689.359 268.022C741.499 347.388 704.222 463.984 606.099 528.446L603.794 529.943C506.076 592.715 385.754 580.205 334.022 501.459L333.417 500.528C282.177 421.184 319.545 305.246 417.285 241.036ZM655.928 289.985C620.041 235.359 525.882 217.554 439.248 274.467C352.614 331.381 331.568 424.87 367.454 479.497C403.341 534.123 497.502 551.928 584.136 495.014C670.769 438.1 691.814 344.611 655.928 289.985ZM272 446.001C280.284 446.001 287 452.717 287 461.001C287 469.286 280.284 476.001 272 476.001H46C37.7158 476.001 31.0001 469.286 31 461.001C31 452.717 37.7157 446.001 46 446.001H272ZM507.551 384.615L589.198 393.898L499.244 396.987C498.533 397.196 497.776 397.296 496.994 397.265C496.574 397.248 496.164 397.193 495.768 397.106L495.248 397.124L495.254 396.976C492.268 396.08 490.147 393.254 490.275 389.995C490.307 389.184 490.476 388.411 490.758 387.698C490.805 387.456 490.863 387.216 490.937 386.978L490.811 386.9L491.114 386.478C491.263 386.1 491.446 385.729 491.666 385.372C492.076 384.705 492.58 384.132 493.149 383.658L545.816 310.667L507.551 384.615ZM242 354.001C250.284 354.001 257 360.717 257 369.001C257 377.286 250.284 384.001 242 384.001H16C7.71578 384.001 1.00009 377.286 1 369.001C1 360.717 7.71573 354.001 16 354.001H242ZM322 261.001C330.284 261.001 337 267.717 337 276.001C337 284.286 330.284 291.001 322 291.001H96C87.7158 291.001 81.0001 284.286 81 276.001C81 267.717 87.7157 261.001 96 261.001H322Z" fill="rgba(22, 163, 74, 0.7)" />
  </svg>
)
